const StrHeroes = [
    'Abaddon',
    'Alchemist',
    'Axe',
    'Beastmaster',
    'Brewmaster',
    'Bristleback',
    'Centaur Warrunner',
    'Chaos Knight',
    'Clockwerk',
    'Dawnbreaker',
    'Doom',
    'Dragon Knight',
    'Earth Spirit',
    'Earthshaker',
    'Elder Titan',
    'Huskar',
    'Io',
    'Kunkka',
    'Legion Commander',
    'Lifestealer',
    'Lycan',
    'Magnus',
    'Mars',
    'Night Stalker',
    'Omniknight',
    'Phoenix',
    'Pudge',
    'Sand King',
    'Slardar',
    'Snapfire',
    'Spirit Breaker',
    'Sven',
    'Tidehunter',
    'Timbersaw',
    'Tiny',
    'Treant Protector',
    'Tusk',
    'Underlord',
    'Undying',
    'Wraith King'
]

const AgiHeroes = [
    'Anti-Mage',
    'Arc Warden',
    'Bloodseeker',
    'Bounty Hunter',
    'Broodmother',
    'Clinkz',
    'Drow Ranger',
    'Ember Spirit',
    'Faceless Void',
    'Gyrocopter',
    'Hoodwink',
    'Juggernaut',
    'Lone Druid',
    'Luna',
    'Medusa',
    'Meepo',
    'Mirana',
    'Monkey King',
    'Morphling',
    'Naga Siren',
    'Nyx Assassin',
    'Pangolier',
    'Phantom Assassin',
    'Phantom Lancer',
    'Razor',
    'Riki',
    'Shadow Fiend',
    'Slark',
    'Sniper',
    'Spectre',
    'Templar Assassin',
    'Terrorblade',
    'Troll Warlord',
    'Ursa',
    'Vengeful Spirit',
    'Venomancer',
    'Viper',
    'Weaver'
]

const IntHeroes = [
    'Ancient Apparition',
    'Bane',
    'Batrider',
    'Chen',
    'Crystal Maiden',
    'Dark Seer',
    'Dark Willow',
    'Dazzle',
    'Death Prophet',
    'Disruptor',
    'Enchantress',
    'Enigma',
    'Grimstroke',
    'Invoker',
    'Jakiro',
    'Keeper of the Light',
    'Leshrac',
    'Lich',
    'Lina',
    'Lion',
    `Nature's Prophet`,
    'Necrophos',
    'Ogre Magi',
    'Oracle',
    'Outworld Destroyer',
    'Puck',
    'Pugna',
    'Queen of Pain',
    'Rubick',
    'Shadow Demon',
    'Shadow Shaman',
    'Silencer',
    'Skywrath Mage',
    'Sorm Spirit',
    'Techies',
    'Tinker',
    'Visage',
    'Void Spirit',
    'Warlock',
    'Windranger',
    'Winter Wyvern',
    'Witch Doctor',
    'Zeus'
]

module.exports = { IntHeroes, AgiHeroes, StrHeroes };